-- Catalog seed for public.games — generated from src/games/registry.ts.
-- Regenerate after adding games; safe to re-run (upsert on id). 65 games.

insert into public.games (id, title, category, contest, blurb, featured) values
  ('color-cards', 'Color Cards', 'card', 'table', 'Match color or number, dump your hand first. UNO-style chaos vs friends or bots.', true),
  ('water-sort', 'Water Sort', 'sort', 'race', 'Pour to sort each color into its own tube. First to sort them all wins.', true),
  ('color-blocks', 'Color Blocks', 'puzzle', 'race', 'Drop blocks, clear full lines. Outlast your rival before the grid fills up.', true),
  ('nuts-and-bolts', 'Nuts and Bolts', 'sort', 'race', 'Stack matching nuts onto bolts until each is one solid color. Fastest sorter wins.', false),
  ('maze-paint', 'Maze Paint', 'puzzle', 'race', 'Slide to fill every tile in one continuous stroke. First to paint the maze wins.', false),
  ('word-finder', 'Word Finder', 'word', 'score', 'Swipe the letter wheel to build words. Highest score after both rounds wins.', true),
  ('merge-2048', '2048', 'puzzle', 'score', 'Swipe to merge matching tiles and chase the biggest number. Beat the bot’s score.', true),
  ('block-blast', 'Block Blast', 'puzzle', 'score', 'Drop blocks, clear lines, and chain combos for a huge score. Outscore your rival.', true),
  ('traffic-jam', 'Traffic Jam', 'puzzle', 'race', 'Slide the cars out of the way to free the red car. First to clear the jam wins.', false),
  ('memory-match', 'Memory Match', 'puzzle', 'table', 'Flip cards to find pairs. Match to go again — most pairs wins. Play a friend or bot.', false),
  ('tic-tac-toe', 'Tic-Tac-Toe', 'board', 'table', 'Three in a row to win. Face an unbeatable bot or a friend pass-and-play.', true),
  ('dots-boxes', 'Dots & Boxes', 'board', 'table', 'Draw lines, close boxes, take extra turns. Claim the most boxes to win.', false),
  ('wordle', 'Secret Word', 'word', 'score', 'Guess the hidden 5-letter word in six tries. Race the bot to crack it first.', true),
  ('pipe-mania', 'Pipe Mania', 'puzzle', 'race', 'Rotate the pipes to connect the water 💧 to the flower 🌸. First to connect wins.', true),
  ('flow-free', 'Flow Free', 'puzzle', 'race', 'Connect matching dots and fill the whole grid without crossing lines. Race to finish.', true),
  ('mancala', 'Mancala', 'board', 'table', 'Sow seeds around the board, capture your opponent’s, and fill your store to win.', false),
  ('reversi', 'Reversi', 'board', 'table', 'Flank your opponent’s discs to flip them. Own the most of the board to win.', true),
  ('golf-solitaire', 'Golf Solitaire', 'card', 'score', 'Clear the columns by playing cards one higher or lower than the waste. Beat the bot.', false),
  ('sudoku-mini', 'Sudoku 6×6', 'puzzle', 'score', 'Fill the 6×6 grid so every row, column and box has 1–6. Race the bot to solve it.', false),
  ('knife-hit', 'Knife Hit', 'arcade', 'score', 'Tap to throw knives into the spinning log — just don’t hit another knife!', true),
  ('flood-it', 'Flood-It', 'sort', 'race', 'Flood the board from the corner and turn every tile one color. First to fill wins.', true),
  ('nonogram', 'Nonogram', 'puzzle', 'race', 'Use the number clues to reveal the hidden pixel-art. Race the bot to solve it.', false),
  ('peg-solitaire', 'Peg Solitaire', 'board', 'score', 'Jump pegs to remove them and aim to leave just one. Outlast the bot.', false),
  ('battleship', 'Battleship', 'board', 'table', 'Hunt and sink the enemy fleet before they sink yours. Vs bot or pass-and-play.', true),
  ('simon-says', 'Simon Says', 'arcade', 'score', 'Watch the flashing pattern and repeat it. Each round gets longer — how far can you go?', true),
  ('whack-a-mole', 'Whack-a-Mole', 'arcade', 'score', 'Tap the moles before they duck — but dodge the bombs! Most points in 30s wins.', true),
  ('blockudoku', 'BlockuDoku', 'puzzle', 'score', 'Drop blocks to fill rows, columns and 3×3 zones. Chain clears for combo points.', true),
  ('minesweeper', 'Minesweeper', 'board', 'score', 'Reveal safe cells using the number clues, flag the mines. Race the bot to clear it.', false),
  ('mahjong-mini', 'Mahjong Mini', 'board', 'score', 'Match free tiles open on a side to clear the layered board. Most pairs wins.', false),
  ('goods-match', 'Goods Match', 'sort', 'score', 'Tap items into the tray and match 3 to clear. Don’t overflow the tray!', false),
  ('hexa-sort', 'Hexa Sort', 'sort', 'score', 'Drop color stacks onto the hex grid; matching neighbors merge and pop when full.', true),
  ('screw-jam', 'Screw Pin Jam', 'sort', 'score', 'Unscrew the pins into matching boxes — fill a box of three to clear it.', false),
  ('helix-jump', 'Helix Jump', 'arcade', 'score', 'Spin the tower so the ball drops through every gap. How deep can you go?', true),
  ('eat-grow', 'Eat & Grow', 'arcade', 'score', 'Drag the hole and swallow everything smaller to grow. Devour the most in 40s.', false),
  ('brick-breaker', 'Brick Breaker', 'arcade', 'score', 'Aim and fire a stream of balls to smash the descending numbered blocks.', false),
  ('tower-war', 'Tower War', 'arcade', 'table', 'Grow troops and drag attacks between towers to capture them all. Real-time vs a bot.', true),
  ('unblock-me', 'Unblock Me', 'puzzle', 'score', 'Slide the wooden blocks aside to free the key block out the gap. Fewer moves = higher score.', false),
  ('liquid-lab', 'Liquid Color Lab', 'sort', 'score', 'Pour and sort the bubbling chemicals into matching test tubes. Beat the bot’s solve.', true),
  ('tile-match', 'Tile Match 3D', 'sort', 'score', 'Tap free tiles from the pile and collect three of a kind before time runs out.', true),
  ('word-wipe', 'Word Wipe', 'word', 'score', 'Swipe touching letters to spell words and collapse the grid. Most points in 75s wins.', false),
  ('checkers', 'Checkers', 'board', 'table', 'Classic draughts — capture by jumping, crown your kings. Vs bot or pass-and-play.', true),
  ('hexa-puzzle', 'Hexa Puzzle', 'puzzle', 'score', 'Drop hexagon pieces onto the board and fill full lines on any of three axes to clear them.', false),
  ('merge-defense', 'Merge Defense', 'arcade', 'score', 'Fire number tiles up the lanes to wipe out descending enemies before they reach your base.', true),
  ('neon-tunnel', 'Neon Tunnel', 'arcade', 'score', 'Steer your ship through the neon tunnel, dodging obstacles for as long as you can.', true),
  ('stack-jump', 'Stack Jump', 'arcade', 'score', 'Tap to drop each sliding block — line it up perfectly to build the tallest tower.', false),
  ('arrow-escape', 'Arrow Escape', 'puzzle', 'race', 'Tap arrows to slide them off the board — clear a path for each one and empty the grid first.', false),
  ('black-hole-solitaire', 'Black Hole', 'card', 'score', 'Swallow the whole table into the black hole — play cards one rank up or down, no suits, no luck.', false),
  ('dungeon-sweeper', 'Dungeon Sweeper', 'puzzle', 'score', 'Minesweeper with monsters. Read the numbers, grab the loot, and reach the exit before your HP runs out.', true),
  ('magnetic-pull', 'Magnetic Pull', 'arcade', 'score', 'Hold the magnets to steer a steel ball down a tightening corridor. How far can you roll?', false),
  ('perfect-slice', 'Perfect Slice', 'puzzle', 'score', 'Cut the shape into perfectly equal pieces with a limited number of straight slices.', false),
  ('word-ladder', 'Word Ladder', 'word', 'race', 'Change one letter at a time to climb from the start word to the goal. First to the top wins.', true),
  ('chess', 'Chess', 'board', 'table', 'The timeless game of kings. Castle, promote, and hunt the checkmate. Vs bot or pass-and-play.', true),
  ('flappy-bird', 'Flappy Bird', 'arcade', 'score', 'Tap to flap the bird between the pipes. One touch is all it takes — how far can you fly?', true),
  ('hangman', 'Hangman', 'word', 'score', 'Guess the hidden word one letter at a time before the stick figure is complete.', false),
  ('klondike', 'Klondike Solitaire', 'card', 'score', 'The classic patience. Build the foundations Ace to King by suit. Beat the bot’s tally.', true),
  ('lights-out', 'Lights Out', 'puzzle', 'race', 'Tap a light to flip it and its neighbours. Switch the whole grid off before the bot does.', false),
  ('fib-2048', '2048 Fibonacci', 'puzzle', 'score', 'Like 2048, but merge consecutive Fibonacci numbers — 1+1=2, 2+3=5, 5+8=13. Chase the high tile.', true),
  ('sokoban', 'Sokoban', 'puzzle', 'race', 'Push every crate onto a target tile — but don’t wedge one in a corner. First to tidy up wins.', false),
  ('bird-sort', 'Bird Sort', 'sort', 'score', 'Move the birds between branches until each branch holds a single colourful flock 🐦', false),
  ('connect-four', 'Connect Four', 'board', 'table', 'Drop your discs and be the first to line up four — across, down, or diagonally. Vs a friend or bot.', true),
  ('snake', 'Classic Snake', 'arcade', 'score', 'Guide the snake to eat food and grow — just don’t hit the walls or your own tail.', false),
  ('word-link', 'Word Link', 'word', 'score', 'Tap the letter wheel to spell words. Find every hidden word before the bot does.', false),
  ('pyramid-solitaire', 'Pyramid Solitaire', 'card', 'score', 'Pair exposed cards that add up to 13 (Kings clear alone) to dismantle the whole pyramid.', false),
  ('dominoes', 'Dominoes', 'board', 'table', 'Match the open ends and be first to empty your hand. Play a friend or the bot.', true),
  ('sliding-puzzle', 'Sliding Puzzle', 'puzzle', 'race', 'Slide the numbered tiles into order using the single empty space. First to solve it wins.', false)
on conflict (id) do update
  set title    = excluded.title,
      category = excluded.category,
      contest  = excluded.contest,
      blurb    = excluded.blurb,
      featured = excluded.featured;
