import type { GameDefinition } from '../engine/types';
import { ICONS } from './icons';

/**
 * The catalog. Adding a game = drop a folder under src/games/<id>/ exporting a
 * GameModule as default, add an icon to icons.tsx, and append one entry here.
 * Everything else (Home, Library, routing, mode picker, 2-player wrapper,
 * scoring) works automatically.
 */
export const GAMES: GameDefinition[] = [
  {
    id: 'color-cards',
    title: 'Color Cards',
    category: 'card',
    contest: 'table',
    blurb: 'Match color or number, dump your hand first. UNO-style chaos vs friends or bots.',
    icon: ICONS['color-cards'],
    accent: '#7a2b2b',
    accent2: '#b8413f',
    load: () => import('./color-cards').then((m) => m.default),
    featured: true
  },
  {
    id: 'water-sort',
    title: 'Water Sort',
    category: 'sort',
    contest: 'race',
    blurb: 'Pour to sort each color into its own tube. First to sort them all wins.',
    icon: ICONS['water-sort'],
    accent: '#3a1d5e',
    accent2: '#6c3fb0',
    load: () => import('./water-sort').then((m) => m.default),
    featured: true
  },
  {
    id: 'color-blocks',
    title: 'Color Blocks',
    category: 'puzzle',
    contest: 'race',
    blurb: 'Drop blocks, clear full lines. Outlast your rival before the grid fills up.',
    icon: ICONS['color-blocks'],
    accent: '#1d2c5e',
    accent2: '#3a59b8',
    load: () => import('./color-blocks').then((m) => m.default),
    featured: true
  },
  {
    id: 'nuts-and-bolts',
    title: 'Nuts and Bolts',
    category: 'sort',
    contest: 'race',
    blurb: 'Stack matching nuts onto bolts until each is one solid color. Fastest sorter wins.',
    icon: ICONS['nuts-and-bolts'],
    accent: '#5e3a1d',
    accent2: '#b8743f'
    ,
    load: () => import('./nuts-and-bolts').then((m) => m.default)
  },
  {
    id: 'maze-paint',
    title: 'Maze Paint',
    category: 'puzzle',
    contest: 'race',
    blurb: 'Slide to fill every tile in one continuous stroke. First to paint the maze wins.',
    icon: ICONS['maze-paint'],
    accent: '#1d4f5e',
    accent2: '#2f9bb8',
    load: () => import('./maze-paint').then((m) => m.default)
  },
  {
    id: 'word-finder',
    title: 'Word Finder',
    category: 'word',
    contest: 'score',
    blurb: 'Swipe the letter wheel to build words. Highest score after both rounds wins.',
    icon: ICONS['word-finder'],
    accent: '#5e1d4a',
    accent2: '#b83f8f',
    load: () => import('./word-finder').then((m) => m.default),
    featured: true
  },
  {
    id: 'merge-2048',
    title: '2048',
    category: 'puzzle',
    contest: 'score',
    blurb: 'Swipe to merge matching tiles and chase the biggest number. Beat the bot’s score.',
    icon: ICONS['merge-2048'],
    accent: '#2b2150',
    accent2: '#5a6cff',
    load: () => import('./merge-2048').then((m) => m.default),
    featured: true
  },
  {
    id: 'block-blast',
    title: 'Block Blast',
    category: 'puzzle',
    contest: 'score',
    blurb: 'Drop blocks, clear lines, and chain combos for a huge score. Outscore your rival.',
    icon: ICONS['block-blast'],
    accent: '#1d3a5e',
    accent2: '#ff8c42',
    load: () => import('./block-blast').then((m) => m.default),
    featured: true
  },
  {
    id: 'traffic-jam',
    title: 'Traffic Jam',
    category: 'puzzle',
    contest: 'race',
    blurb: 'Slide the cars out of the way to free the red car. First to clear the jam wins.',
    icon: ICONS['traffic-jam'],
    accent: '#5e1d1d',
    accent2: '#ff4d4d',
    load: () => import('./traffic-jam').then((m) => m.default)
  },
  {
    id: 'memory-match',
    title: 'Memory Match',
    category: 'puzzle',
    contest: 'table',
    blurb: 'Flip cards to find pairs. Match to go again — most pairs wins. Play a friend or bot.',
    icon: ICONS['memory-match'],
    accent: '#1d4f3a',
    accent2: '#2f9e4f',
    load: () => import('./memory-match').then((m) => m.default)
  },
  {
    id: 'tic-tac-toe',
    title: 'Tic-Tac-Toe',
    category: 'board',
    contest: 'table',
    blurb: 'Three in a row to win. Face an unbeatable bot or a friend pass-and-play.',
    icon: ICONS['tic-tac-toe'],
    accent: '#1d2c5e',
    accent2: '#41a0ff',
    load: () => import('./tic-tac-toe').then((m) => m.default),
    featured: true
  },
  {
    id: 'dots-boxes',
    title: 'Dots & Boxes',
    category: 'board',
    contest: 'table',
    blurb: 'Draw lines, close boxes, take extra turns. Claim the most boxes to win.',
    icon: ICONS['dots-boxes'],
    accent: '#3a1d5e',
    accent2: '#41d3bd',
    load: () => import('./dots-boxes').then((m) => m.default)
  },
  {
    id: 'wordle',
    title: 'Secret Word',
    category: 'word',
    contest: 'score',
    blurb: 'Guess the hidden 5-letter word in six tries. Race the bot to crack it first.',
    icon: ICONS['wordle'],
    accent: '#1d3a2c',
    accent2: '#2f9e4f',
    load: () => import('./wordle').then((m) => m.default),
    featured: true
  },
  {
    id: 'pipe-mania',
    title: 'Pipe Mania',
    category: 'puzzle',
    contest: 'race',
    blurb: 'Rotate the pipes to connect the water 💧 to the flower 🌸. First to connect wins.',
    icon: ICONS['pipe-mania'],
    accent: '#1d4f5e',
    accent2: '#41d3bd',
    load: () => import('./pipe-mania').then((m) => m.default),
    featured: true
  },
  {
    id: 'flow-free',
    title: 'Flow Free',
    category: 'puzzle',
    contest: 'race',
    blurb: 'Connect matching dots and fill the whole grid without crossing lines. Race to finish.',
    icon: ICONS['flow-free'],
    accent: '#2b1d5e',
    accent2: '#ff5d73',
    load: () => import('./flow-free').then((m) => m.default),
    featured: true
  },
  {
    id: 'mancala',
    title: 'Mancala',
    category: 'board',
    contest: 'table',
    blurb: 'Sow seeds around the board, capture your opponent’s, and fill your store to win.',
    icon: ICONS['mancala'],
    accent: '#5e3a1d',
    accent2: '#c4843f',
    load: () => import('./mancala').then((m) => m.default)
  },
  {
    id: 'reversi',
    title: 'Reversi',
    category: 'board',
    contest: 'table',
    blurb: 'Flank your opponent’s discs to flip them. Own the most of the board to win.',
    icon: ICONS['reversi'],
    accent: '#1d4f3a',
    accent2: '#2f9e4f',
    load: () => import('./reversi').then((m) => m.default),
    featured: true
  },
  {
    id: 'golf-solitaire',
    title: 'Golf Solitaire',
    category: 'card',
    contest: 'score',
    blurb: 'Clear the columns by playing cards one higher or lower than the waste. Beat the bot.',
    icon: ICONS['golf-solitaire'],
    accent: '#1d3a2c',
    accent2: '#51e08a',
    load: () => import('./golf-solitaire').then((m) => m.default)
  },
  {
    id: 'sudoku-mini',
    title: 'Sudoku 6×6',
    category: 'puzzle',
    contest: 'score',
    blurb: 'Fill the 6×6 grid so every row, column and box has 1–6. Race the bot to solve it.',
    icon: ICONS['sudoku-mini'],
    accent: '#1d2c5e',
    accent2: '#41a0ff',
    load: () => import('./sudoku-mini').then((m) => m.default)
  },
  {
    id: 'knife-hit',
    title: 'Knife Hit',
    category: 'arcade',
    contest: 'score',
    blurb: 'Tap to throw knives into the spinning log — just don’t hit another knife!',
    icon: ICONS['knife-hit'],
    accent: '#5e1d1d',
    accent2: '#ff8c42',
    load: () => import('./knife-hit').then((m) => m.default),
    featured: true
  },
  {
    id: 'flood-it',
    title: 'Flood-It',
    category: 'sort',
    contest: 'race',
    blurb: 'Flood the board from the corner and turn every tile one color. First to fill wins.',
    icon: ICONS['flood-it'],
    accent: '#2b1d5e',
    accent2: '#41d3bd',
    load: () => import('./flood-it').then((m) => m.default),
    featured: true
  },
  {
    id: 'nonogram',
    title: 'Nonogram',
    category: 'puzzle',
    contest: 'race',
    blurb: 'Use the number clues to reveal the hidden pixel-art. Race the bot to solve it.',
    icon: ICONS['nonogram'],
    accent: '#1d4f3a',
    accent2: '#41d3bd',
    load: () => import('./nonogram').then((m) => m.default)
  },
  {
    id: 'peg-solitaire',
    title: 'Peg Solitaire',
    category: 'board',
    contest: 'score',
    blurb: 'Jump pegs to remove them and aim to leave just one. Outlast the bot.',
    icon: ICONS['peg-solitaire'],
    accent: '#5e3a1d',
    accent2: '#c4843f',
    load: () => import('./peg-solitaire').then((m) => m.default)
  },
  {
    id: 'battleship',
    title: 'Battleship',
    category: 'board',
    contest: 'table',
    blurb: 'Hunt and sink the enemy fleet before they sink yours. Vs bot or pass-and-play.',
    icon: ICONS['battleship'],
    accent: '#13294f',
    accent2: '#41a0ff',
    load: () => import('./battleship').then((m) => m.default),
    featured: true
  },
  {
    id: 'simon-says',
    title: 'Simon Says',
    category: 'arcade',
    contest: 'score',
    blurb: 'Watch the flashing pattern and repeat it. Each round gets longer — how far can you go?',
    icon: ICONS['simon-says'],
    accent: '#3a1d5e',
    accent2: '#8367ff',
    load: () => import('./simon-says').then((m) => m.default),
    featured: true
  },
  {
    id: 'whack-a-mole',
    title: 'Whack-a-Mole',
    category: 'arcade',
    contest: 'score',
    blurb: 'Tap the moles before they duck — but dodge the bombs! Most points in 30s wins.',
    icon: ICONS['whack-a-mole'],
    accent: '#5e3a1d',
    accent2: '#51e08a',
    load: () => import('./whack-a-mole').then((m) => m.default),
    featured: true
  },
  {
    id: 'blockudoku',
    title: 'BlockuDoku',
    category: 'puzzle',
    contest: 'score',
    blurb: 'Drop blocks to fill rows, columns and 3×3 zones. Chain clears for combo points.',
    icon: ICONS['blockudoku'],
    accent: '#1d2c5e',
    accent2: '#8367ff',
    load: () => import('./blockudoku').then((m) => m.default),
    featured: true
  },
  {
    id: 'minesweeper',
    title: 'Minesweeper',
    category: 'board',
    contest: 'score',
    blurb: 'Reveal safe cells using the number clues, flag the mines. Race the bot to clear it.',
    icon: ICONS['minesweeper'],
    accent: '#1d2c5e',
    accent2: '#41a0ff',
    load: () => import('./minesweeper').then((m) => m.default)
  },
  {
    id: 'mahjong-mini',
    title: 'Mahjong Mini',
    category: 'board',
    contest: 'score',
    blurb: 'Match free tiles open on a side to clear the layered board. Most pairs wins.',
    icon: ICONS['mahjong-mini'],
    accent: '#1d4f3a',
    accent2: '#41d3bd',
    load: () => import('./mahjong-mini').then((m) => m.default)
  },
  {
    id: 'goods-match',
    title: 'Goods Match',
    category: 'sort',
    contest: 'score',
    blurb: 'Tap items into the tray and match 3 to clear. Don’t overflow the tray!',
    icon: ICONS['goods-match'],
    accent: '#5e3a1d',
    accent2: '#ffd166',
    load: () => import('./goods-match').then((m) => m.default)
  },
  {
    id: 'hexa-sort',
    title: 'Hexa Sort',
    category: 'sort',
    contest: 'score',
    blurb: 'Drop color stacks onto the hex grid; matching neighbors merge and pop when full.',
    icon: ICONS['hexa-sort'],
    accent: '#3a1d5e',
    accent2: '#ff5d73',
    load: () => import('./hexa-sort').then((m) => m.default),
    featured: true
  },
  {
    id: 'screw-jam',
    title: 'Screw Pin Jam',
    category: 'sort',
    contest: 'score',
    blurb: 'Unscrew the pins into matching boxes — fill a box of three to clear it.',
    icon: ICONS['screw-jam'],
    accent: '#5e3a1d',
    accent2: '#ff8c42',
    load: () => import('./screw-jam').then((m) => m.default)
  },
  {
    id: 'helix-jump',
    title: 'Helix Jump',
    category: 'arcade',
    contest: 'score',
    blurb: 'Spin the tower so the ball drops through every gap. How deep can you go?',
    icon: ICONS['helix-jump'],
    accent: '#2b1d5e',
    accent2: '#41d3bd',
    load: () => import('./helix-jump').then((m) => m.default),
    featured: true
  },
  {
    id: 'eat-grow',
    title: 'Eat & Grow',
    category: 'arcade',
    contest: 'score',
    blurb: 'Drag the hole and swallow everything smaller to grow. Devour the most in 40s.',
    icon: ICONS['eat-grow'],
    accent: '#1d4f3a',
    accent2: '#51e08a',
    load: () => import('./eat-grow').then((m) => m.default)
  },
  {
    id: 'brick-breaker',
    title: 'Brick Breaker',
    category: 'arcade',
    contest: 'score',
    blurb: 'Aim and fire a stream of balls to smash the descending numbered blocks.',
    icon: ICONS['brick-breaker'],
    accent: '#1d4f5e',
    accent2: '#51e08a',
    load: () => import('./brick-breaker').then((m) => m.default)
  },
  {
    id: 'tower-war',
    title: 'Tower War',
    category: 'arcade',
    contest: 'table',
    blurb: 'Grow troops and drag attacks between towers to capture them all. Real-time vs a bot.',
    icon: ICONS['tower-war'],
    accent: '#5e1d1d',
    accent2: '#41a0ff',
    load: () => import('./tower-war').then((m) => m.default),
    featured: true
  },
  {
    id: 'unblock-me',
    title: 'Unblock Me',
    category: 'puzzle',
    contest: 'score',
    blurb: 'Slide the wooden blocks aside to free the key block out the gap. Fewer moves = higher score.',
    icon: ICONS['unblock-me'],
    accent: '#5e3a1d',
    accent2: '#c4843f',
    load: () => import('./unblock-me').then((m) => m.default)
  },
  {
    id: 'liquid-lab',
    title: 'Liquid Color Lab',
    category: 'sort',
    contest: 'score',
    blurb: 'Pour and sort the bubbling chemicals into matching test tubes. Beat the bot’s solve.',
    icon: ICONS['liquid-lab'],
    accent: '#1d4f5e',
    accent2: '#41d3bd',
    load: () => import('./liquid-lab').then((m) => m.default),
    featured: true
  },
  {
    id: 'tile-match',
    title: 'Tile Match 3D',
    category: 'sort',
    contest: 'score',
    blurb: 'Tap free tiles from the pile and collect three of a kind before time runs out.',
    icon: ICONS['tile-match'],
    accent: '#3a1d5e',
    accent2: '#ff5d73',
    load: () => import('./tile-match').then((m) => m.default),
    featured: true
  },
  {
    id: 'word-wipe',
    title: 'Word Wipe',
    category: 'word',
    contest: 'score',
    blurb: 'Swipe touching letters to spell words and collapse the grid. Most points in 75s wins.',
    icon: ICONS['word-wipe'],
    accent: '#1d2c5e',
    accent2: '#41a0ff',
    load: () => import('./word-wipe').then((m) => m.default)
  },
  {
    id: 'checkers',
    title: 'Checkers',
    category: 'board',
    contest: 'table',
    blurb: 'Classic draughts — capture by jumping, crown your kings. Vs bot or pass-and-play.',
    icon: ICONS['checkers'],
    accent: '#1d4f3a',
    accent2: '#e24b4b',
    load: () => import('./checkers').then((m) => m.default),
    featured: true
  },
  {
    id: 'hexa-puzzle',
    title: 'Hexa Puzzle',
    category: 'puzzle',
    contest: 'score',
    blurb: 'Drop hexagon pieces onto the board and fill full lines on any of three axes to clear them.',
    icon: ICONS['hexa-puzzle'],
    accent: '#3a1d5e',
    accent2: '#8367ff',
    load: () => import('./hexa-puzzle').then((m) => m.default)
  },
  {
    id: 'merge-defense',
    title: 'Merge Defense',
    category: 'arcade',
    contest: 'score',
    blurb: 'Fire number tiles up the lanes to wipe out descending enemies before they reach your base.',
    icon: ICONS['merge-defense'],
    accent: '#1d2c5e',
    accent2: '#ff5d73',
    load: () => import('./merge-defense').then((m) => m.default),
    featured: true
  },
  {
    id: 'neon-tunnel',
    title: 'Neon Tunnel',
    category: 'arcade',
    contest: 'score',
    blurb: 'Steer your ship through the neon tunnel, dodging obstacles for as long as you can.',
    icon: ICONS['neon-tunnel'],
    accent: '#3a1d5e',
    accent2: '#bc13fe',
    load: () => import('./neon-tunnel').then((m) => m.default),
    featured: true
  },
  {
    id: 'stack-jump',
    title: 'Stack Jump',
    category: 'arcade',
    contest: 'score',
    blurb: 'Tap to drop each sliding block — line it up perfectly to build the tallest tower.',
    icon: ICONS['stack-jump'],
    accent: '#1d4f5e',
    accent2: '#00f3ff',
    load: () => import('./stack-jump').then((m) => m.default)
  },
  {
    id: 'arrow-escape',
    title: 'Arrow Escape',
    category: 'puzzle',
    contest: 'race',
    blurb: 'Tap arrows to slide them off the board — clear a path for each one and empty the grid first.',
    icon: ICONS['arrow-escape'],
    accent: '#1d4f5e',
    accent2: '#00f3ff',
    load: () => import('./arrow-escape').then((m) => m.default)
  },
  {
    id: 'black-hole-solitaire',
    title: 'Black Hole',
    category: 'card',
    contest: 'score',
    blurb: 'Swallow the whole table into the black hole — play cards one rank up or down, no suits, no luck.',
    icon: ICONS['black-hole-solitaire'],
    accent: '#2a1247',
    accent2: '#6c3fb0',
    load: () => import('./black-hole-solitaire').then((m) => m.default)
  },
  {
    id: 'dungeon-sweeper',
    title: 'Dungeon Sweeper',
    category: 'puzzle',
    contest: 'score',
    blurb: 'Minesweeper with monsters. Read the numbers, grab the loot, and reach the exit before your HP runs out.',
    icon: ICONS['dungeon-sweeper'],
    accent: '#1d2c5e',
    accent2: '#7fc7ff',
    load: () => import('./dungeon-sweeper').then((m) => m.default),
    featured: true
  },
  {
    id: 'magnetic-pull',
    title: 'Magnetic Pull',
    category: 'arcade',
    contest: 'score',
    blurb: 'Hold the magnets to steer a steel ball down a tightening corridor. How far can you roll?',
    icon: ICONS['magnetic-pull'],
    accent: '#1d4f5e',
    accent2: '#00f3ff',
    load: () => import('./magnetic-pull').then((m) => m.default)
  },
  {
    id: 'perfect-slice',
    title: 'Perfect Slice',
    category: 'puzzle',
    contest: 'score',
    blurb: 'Cut the shape into perfectly equal pieces with a limited number of straight slices.',
    icon: ICONS['perfect-slice'],
    accent: '#3a1d5e',
    accent2: '#41d3bd',
    load: () => import('./perfect-slice').then((m) => m.default)
  },
  {
    id: 'word-ladder',
    title: 'Word Ladder',
    category: 'word',
    contest: 'race',
    blurb: 'Change one letter at a time to climb from the start word to the goal. First to the top wins.',
    icon: ICONS['word-ladder'],
    accent: '#7a2b2b',
    accent2: '#ff9f43',
    load: () => import('./word-ladder').then((m) => m.default),
    featured: true
  },
  {
    id: 'chess',
    title: 'Chess',
    category: 'board',
    contest: 'table',
    blurb: 'The timeless game of kings. Castle, promote, and hunt the checkmate. Vs bot or pass-and-play.',
    icon: ICONS['chess'],
    accent: '#1d2c3a',
    accent2: '#8a9bb8',
    load: () => import('./chess').then((m) => m.default),
    featured: true
  },
  {
    id: 'flappy-bird',
    title: 'Flappy Bird',
    category: 'arcade',
    contest: 'score',
    blurb: 'Tap to flap the bird between the pipes. One touch is all it takes — how far can you fly?',
    icon: ICONS['flappy-bird'],
    accent: '#1d4f3a',
    accent2: '#ffd166',
    load: () => import('./flappy-bird').then((m) => m.default),
    featured: true
  },
  {
    id: 'hangman',
    title: 'Hangman',
    category: 'word',
    contest: 'score',
    blurb: 'Guess the hidden word one letter at a time before the stick figure is complete.',
    icon: ICONS['hangman'],
    accent: '#5e3a1d',
    accent2: '#ff8c42',
    load: () => import('./hangman').then((m) => m.default)
  },
  {
    id: 'klondike',
    title: 'Klondike Solitaire',
    category: 'card',
    contest: 'score',
    blurb: 'The classic patience. Build the foundations Ace to King by suit. Beat the bot’s tally.',
    icon: ICONS['klondike'],
    accent: '#1d3a2c',
    accent2: '#51e08a',
    load: () => import('./klondike').then((m) => m.default),
    featured: true
  },
  {
    id: 'lights-out',
    title: 'Lights Out',
    category: 'puzzle',
    contest: 'race',
    blurb: 'Tap a light to flip it and its neighbours. Switch the whole grid off before the bot does.',
    icon: ICONS['lights-out'],
    accent: '#1a2336',
    accent2: '#ffd166',
    load: () => import('./lights-out').then((m) => m.default)
  },
  {
    id: 'fib-2048',
    title: '2048 Fibonacci',
    category: 'puzzle',
    contest: 'score',
    blurb: 'Like 2048, but merge consecutive Fibonacci numbers — 1+1=2, 2+3=5, 5+8=13. Chase the high tile.',
    icon: ICONS['fib-2048'],
    accent: '#6c4ad6',
    accent2: '#f59563',
    load: () => import('./fib-2048').then((m) => m.default),
    featured: true
  },
  {
    id: 'sokoban',
    title: 'Sokoban',
    category: 'puzzle',
    contest: 'race',
    blurb: 'Push every crate onto a target tile — but don’t wedge one in a corner. First to tidy up wins.',
    icon: ICONS['sokoban'],
    accent: '#10151d',
    accent2: '#caa46a',
    load: () => import('./sokoban').then((m) => m.default)
  },
  {
    id: 'bird-sort',
    title: 'Bird Sort',
    category: 'sort',
    contest: 'score',
    blurb: 'Move the birds between branches until each branch holds a single colourful flock 🐦',
    icon: ICONS['bird-sort'],
    accent: '#1d3a2c',
    accent2: '#ff5d73',
    load: () => import('./bird-sort').then((m) => m.default)
  },
  {
    id: 'connect-four',
    title: 'Connect Four',
    category: 'board',
    contest: 'table',
    blurb: 'Drop your discs and be the first to line up four — across, down, or diagonally. Vs a friend or bot.',
    icon: ICONS['connect-four'],
    accent: '#15347e',
    accent2: '#ffd166',
    load: () => import('./connect-four').then((m) => m.default),
    featured: true
  },
  {
    id: 'snake',
    title: 'Classic Snake',
    category: 'arcade',
    contest: 'score',
    blurb: 'Guide the snake to eat food and grow — just don’t hit the walls or your own tail.',
    icon: ICONS['snake'],
    accent: '#10241a',
    accent2: '#51e08a',
    load: () => import('./snake').then((m) => m.default)
  },
  {
    id: 'word-link',
    title: 'Word Link',
    category: 'word',
    contest: 'score',
    blurb: 'Tap the letter wheel to spell words. Find every hidden word before the bot does.',
    icon: ICONS['word-link'],
    accent: '#1b2440',
    accent2: '#ffd166',
    load: () => import('./word-link').then((m) => m.default)
  },
  {
    id: 'pyramid-solitaire',
    title: 'Pyramid Solitaire',
    category: 'card',
    contest: 'score',
    blurb: 'Pair exposed cards that add up to 13 (Kings clear alone) to dismantle the whole pyramid.',
    icon: ICONS['pyramid-solitaire'],
    accent: '#2b3a66',
    accent2: '#e0b35c',
    load: () => import('./pyramid-solitaire').then((m) => m.default)
  },
  {
    id: 'dominoes',
    title: 'Dominoes',
    category: 'board',
    contest: 'table',
    blurb: 'Match the open ends and be first to empty your hand. Play a friend or the bot.',
    icon: ICONS['dominoes'],
    accent: '#3a3327',
    accent2: '#f4f1e8',
    load: () => import('./dominoes').then((m) => m.default),
    featured: true
  },
  {
    id: 'sliding-puzzle',
    title: 'Sliding Puzzle',
    category: 'puzzle',
    contest: 'race',
    blurb: 'Slide the numbered tiles into order using the single empty space. First to solve it wins.',
    icon: ICONS['sliding-puzzle'],
    accent: '#1a2336',
    accent2: '#5b8cff',
    load: () => import('./sliding-puzzle').then((m) => m.default)
  }
];

export const getGame = (id: string) => GAMES.find((g) => g.id === id);
